### ISSUE TITLE
affiliation xml:lang attribute

### ISSUE THREAD

**Issue by mfdion** [datacite/schema#57] opened 2019-07-18 18:18 UTC
Not entirely sure this is the right place to bring this up, but it is related to the DataCite schema. When trying to update records (using DataCite schema 4.1), we are now encountering errors regarding the contributor and creator affiliations. We would previously have two values with an xml:lang attribute on each, for example:
`<affiliation xml:lang="en">National Research Council Canada</affiliation>`
`<affiliation xml:lang="fr">Conseil national de recherches Canada</affiliation>`

This no longer validates with the recent updates. Is this intended? Should the update be made just to strip the xml:lang attribute (see below), or is there another/better way to convey this?
`<affiliation>National Research Council Canada</affiliation>`
`<affiliation>Conseil national de recherches Canada</affiliation>`

Thank you,
Marc Dion

**Comment by mfenner** [comment] 2019-07-18 18:56
@mfdion the issue is that `xml:lang` is only supported on some elements, and that does not include `affiliation`. 

We are very close to releasing version 4.3 of the schema, which will add optional affiliation identifiers. You can then say `<affiliation affiliationIdentifier="https://ror.org/04mte1k06" affiliationIdentifierScheme="ROR">National Research Council Canada</affiliation>`. I think this is the better solution, as our schema doesn't support the concept of alternate names for the same affiliation as we for example do for titles. In your solution a machine might get confused, thinking this is two different affiliations. ROR identifiers support names in multiple languages, in the case of https://ror.org/04mte1k06 you have 

```
"labels": [
  {
    "label": "Conseil National de Recherches Canada",
    "iso639": "fr"
  }
]
```

So remove `xml:lang` and optionally include the affiliationIdentifier. You can also use an ISNI instead of ROR if you prefer. The official release is soon, but both the test and production system for DOI registration already support this.

**Comment by mfenner** [comment] 2019-07-18 19:35
I made some changes to the affiliation element, and it seems we are now more strict regarding `xml:lang`. This was not intended, but aligns the schema closer with the schema documentation.

**Comment by mfdion** [comment] 2019-07-19 14:19
This is all great to know, thank you!

Multiple affiliation confusion is the situation we'd like to avoid. I suppose a better solution for the interim would be to only include one entry per affiliation until we work out an implementation for affiliation IDs.

**Comment by mfenner** [comment] 2019-07-19 14:27
Great. I will close the issue. Please open a new issue if you need help with implementing affiliation identifiers. But it might be easiest to just wait two weeks for the announcement and documentation.

**Closed by mfenner** 2019-07-19 14:27 UTC
Labels: discussion
